# This file contains project configuration


# Value that the ROM will be filled with
FillValue = 0xFF


## Header constants (passed to RGBFIX)

ROMVersion = 1

# 4-ASCII letter game ID
GameID = MBGB

# Game title, up to 11 ASCII chars
GameTitle = SOFTBOUNDGB

# New licensee, 2 ASCII chars
NewLicensee = HB # Licensed by Homebrew (lel)
# Old licensee, please set to 0x33 (required to get SGB compatibility)
OldLicensee = 0x33

# MBC type, tells which hardware is in the cart
# MBC5             0x19
# MBC5+RAM         0x1A
# MBC5+RAM+BATTERY 0x1B
MBCType = 0x1B

# ROM size is automatic

# None 0x00
#   8k 0x02
#  32k 0x03
# 128k 0x04
#  64k 0x05
SRAMSize = 0x03

# ROM name
ROMName = motherboard
ROMExt  = gb


# Compilation parameters, uncomment to apply

# Game Boy Color compatible
# FXFLAGS += -c
# Game Boy Color required
# FXFLAGS += -C

# Super Game Boy compatible
FXFLAGS += -s

# Game Boy mode
LDFLAGS += -d

# 32k mode
# LDFLAGS += -t



# `superfamiconv`: Converts images to SNES graphics format, used to encode the SGB border
# To build SuperFamiconv here; not necessary if you already have one
superfamiconv: $(SRCDIR)/tools/SuperFamiconv/bin/superfamiconv
.PHONY: superfamiconv

$(SRCDIR)/tools/SuperFamiconv/bin/superfamiconv: $(SRCDIR)/tools/SuperFamiconv
	cd $< && $(MAKE)

# To clone SuperFamiconv's GitHub repo (only has to be done once)
$(SRCDIR)/tools/SuperFamiconv:
	[ -d $@  -a  -f $@/Makefile ] || git clone https://github.com/Optiroc/SuperFamiconv.git $@
